spring.application.name=ApiGateway
server.port=8069
#eureeka config
eureka.client.register-with-eureka=true
eureka.client.service-url.default-zone =http://eureeka:8761/eureka-server
#logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
#keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://eureeka:8045/realms/job_board_realm