spring.cloud.config.fail-fast=true
spring.application.name=Candidat
server.port=8080
spring.cloud.config.import-check.enabled=false
#server.servlet.context-path=/candidat

#H2 (see http://www.h2database.com/html/features.html)
spring.h2.console.enabled=true
spring.h2.console.path=/h2

#Datasource
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./Candidat/Database/Data/Candidats;AUTO_SERVER=TRUE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#eureka config
eureka.client.service-url.default-zone=http://eureeka:8761/eureka-server
eureka.client.register-with-eureka=true